#!/bin/bash
#
# evening-summary-local.sh — AKIOR Task 78
#
# Local-only evening summary via Ollama. Reads today's action ledger
# and decision log, filters noise, sends to qwen2.5-coder:7b for
# summarization, writes structured markdown to evidence/terminal/.
#
# Policy: LOCAL-ONLY. No paid API (Anthropic, OpenAI, Groq, etc.).
# Only network target: 127.0.0.1:11434 (local Ollama).
#
# Invoked by launchd agent com.akior.evening-summary-local (daily 20:00).

set -u

LOCKDIR="/tmp/akior-evening-summary-local.lock"
LOG="${HOME}/akior/evidence/terminal/evening-summary-autonomous.log"
OUTPUT="${HOME}/akior/evidence/terminal/evening-summary-latest.md"
OLLAMA="${HOME}/akior/scripts/ollama-local-llm.sh"
MODEL="qwen2.5-coder:7b"
ACTION_LEDGER="${HOME}/akior/ledgers/action.md"
DECISION_LEDGER="${HOME}/akior/ledgers/decision.md"

TODAY=$(date +"%Y-%m-%d")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

mkdir -p "$(dirname "$LOG")" "$(dirname "$OUTPUT")"

ts() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log_line() { printf '[%s] %s\n' "$(ts)" "$*" >> "$LOG"; }

# Lockfile
if ! mkdir "$LOCKDIR" 2>/dev/null; then
  log_line "SKIP overlap: lock held at ${LOCKDIR}"
  exit 0
fi
echo "$$" > "${LOCKDIR}/pid"
trap 'rm -rf "$LOCKDIR"' EXIT INT TERM

log_line "START pid=$$ evening-summary-local"

# --- Gather today's ledger data ---

# Action ledger: filter today, deduplicate TMUX_WATCHDOG to a count
ACTION_RAW=$(grep "$TODAY" "$ACTION_LEDGER" 2>/dev/null || true)
WATCHDOG_COUNT=$(echo "$ACTION_RAW" | grep -c "TMUX_WATCHDOG" || true)
ACTION_MEANINGFUL=$(echo "$ACTION_RAW" | grep -v "TMUX_WATCHDOG" | head -40)
ACTION_LINE_COUNT=$(echo "$ACTION_MEANINGFUL" | grep -c "." || true)

# Decision ledger: filter today
DECISION_RAW=$(grep "$TODAY" "$DECISION_LEDGER" 2>/dev/null | head -20 || true)
DECISION_LINE_COUNT=$(echo "$DECISION_RAW" | grep -c "." || true)

# Recent evidence files from today
RECENT_EVIDENCE=$(find "${HOME}/akior/evidence/terminal" -name "*.md" -newer "${HOME}/akior/ledgers/action.md" -mtime 0 2>/dev/null | head -10 || true)
EVIDENCE_COUNT=$(echo "$RECENT_EVIDENCE" | grep -c "." || true)

log_line "DATA action=${ACTION_LINE_COUNT} meaningful (${WATCHDOG_COUNT} watchdog filtered), decisions=${DECISION_LINE_COUNT}, evidence_files=${EVIDENCE_COUNT}"

# --- Build prompt ---

# Cap total input to avoid overloading 7B model context
PROMPT_INPUT="Today is ${TODAY}.

ACTION LEDGER (${ACTION_LINE_COUNT} meaningful entries, ${WATCHDOG_COUNT} watchdog heartbeats filtered):
${ACTION_MEANINGFUL}

DECISION LOG (${DECISION_LINE_COUNT} entries):
${DECISION_RAW}"

# Truncate to ~3000 chars if very long day
PROMPT_INPUT=$(echo "$PROMPT_INPUT" | head -80 | cut -c1-4000)

PROMPT="You are AKIOR's local evening summary generator. Produce a concise end-of-day summary in markdown format with these sections:
## Actions Taken
## Decisions Made
## Outstanding Items
## System Status

Be brief. One to three bullet points per section. If a section has no entries, write 'None today.' Do not invent information. Base the summary only on the data below.

${PROMPT_INPUT}"

# --- Call local Ollama ---

if [ ! -x "$OLLAMA" ]; then
  log_line "FAIL ollama wrapper not found at ${OLLAMA}"
  exit 2
fi

log_line "INVOKE ollama model=${MODEL}"
RAW_RESULT=$("$OLLAMA" "$MODEL" "$PROMPT" 2>&1)
RC=$?

if [ $RC -ne 0 ]; then
  log_line "FAIL ollama exit=${RC}"
  exit $RC
fi

# Extract content from JSON envelope
SUMMARY=$(echo "$RAW_RESULT" | python3 -c '
import sys, json
try:
    d = json.loads(sys.stdin.read())
    if d.get("ok"):
        print(d["content"])
    else:
        print("ERROR: " + d.get("error", "unknown"))
        sys.exit(1)
except Exception as e:
    print("PARSE ERROR: " + str(e))
    sys.exit(1)
' 2>&1)
PARSE_RC=$?

if [ $PARSE_RC -ne 0 ]; then
  log_line "FAIL parse error: ${SUMMARY}"
  exit 3
fi

# --- Write output artifact ---

cat > "$OUTPUT" <<EOF
# AKIOR Evening Summary

**Date:** ${TODAY}
**Generated:** ${TIMESTAMP}
**Mode:** LOCAL-ONLY (qwen2.5-coder:7b via Ollama)
**Source:** action.md (${ACTION_LINE_COUNT} entries + ${WATCHDOG_COUNT} watchdog) · decision.md (${DECISION_LINE_COUNT} entries)

---

${SUMMARY}

---
*Generated by evening-summary-local.sh — no paid API used*
EOF

# Append to action ledger
echo "| ${TIMESTAMP} | EVENING_SUMMARY_LOCAL | COMPLETE — written to ${OUTPUT} |" >> "$ACTION_LEDGER"

log_line "OK output=${OUTPUT}"
exit 0
